{"bug_id": "62642", "title": "Bug 62642proper handling of ExceptionInIntializer inside <clinit in presence of after throwing advice", "description": "When a <clinit of a class contains after throwing advice that may catchExceptionInInitializer errors due to an embedded advice aspectOf() thatfails,the ExceptionInIntializer error does not get properly reported.For the example below:public class Main {static int x = 13;int y;public Main() {y= 14;}public static void main(String args[]){ Main m = new Main();m.y = 3;System.out.println(\"hi\");}}aspect Aspect {before () :within(){ System.out.println(\"BEFORE \" + thisJoinPointStaticPart.getKind() +\" at \" + thisJoinPointStaticPart.getSourceLocation());}after (): within(){ System.out.println(\"AFTER \" + thisJoinPointStaticPart.getKind() +\" at \" + thisJoinPointStaticPart.getSourceLocation());}}....when compiled with ajc, and then run,the following exception is given,Exception in thread \"main\" java.lang.NoClassDefFoundErrorat Main.<clinit(Main.java:1)when really one wants the following:Exception in thread \"main\" java.lang.ExceptionInInitializerErrorat Main. ...Caused by: org.aspectj.lang.NoAspectBoundException: Aspectat Aspect.aspectOf ..Here is a fix ... I give the decompiled <clinit for Main.java and indicate withcomments,look for LJH ,what can be woven to fix it.Basically, the catchblock for after throwing,when in <clinit,should first check if thecaught exception if a ExceptionInInitializerError, and if so just throw it. static{org.aspectj.runtime.reflect.Factory r1;java.lang.Throwable r2, r31;int $i0;r1 = new Factory(\"Main.java\", Class.forName(\"Main\"));ajc$tjp0 = r1.makeSJP(\"fieldset\", r1.makeFieldSig(\"8xMainint\"), 2);ajc$tjp1 = r1.makeSJP(\"staticinitialization\",r1.makeInitializerSig(\"8Main\"), 2);ajc$tjp10 = r1.makeSJP(\"preinitialization\",r1.makeConstructorSig(\"1Main\"), 5);ajc$tjp2 = r1.makeSJP(\"fieldset\", r1.makeFieldSig(\"0yMainint\"), 6);ajc$tjp3 = r1.makeSJP(\"constructorexecution\",r1.makeConstructorSig(\"1Main\"), 6);ajc$tjp4 = r1.makeSJP(\"constructorcall\",r1.makeConstructorSig(\"1Main\"), 10);ajc$tjp5 = r1.makeSJP(\"fieldset\", r1.makeFieldSig(\"0yMainint\"), 11);ajc$tjp6 = r1.makeSJP(\"fieldget\",r1.makeFieldSig(\"19outjava.lang.Systemjava.io.PrintStream\"), 12);ajc$tjp7 = r1.makeSJP(\"methodcall\",r1.makeMethodSig(\"1printlnjava.io.PrintStreamjava.lang.String:arg0:void\"),12);ajc$tjp8 = r1.makeSJP(\"methodexecution\",r1.makeMethodSig(\"9mainMain[Ljava.lang.String;:args:void\"), 10);ajc$tjp9 = r1.makeSJP(\"initialization\",r1.makeConstructorSig(\"1Main\"), 6); try{Aspect.aspectOf().ajc$before$Aspect$1$36f01b1c(ajc$tjp1);$i0 = 13;try{Aspect.aspectOf().ajc$before$Aspect$1$36f01b1c(ajc$tjp0);x = $i0;}catch (Throwable $r30){/ LJH insert here /if ($r30 instanceof ExceptionInIntializerError) //throw($r30); ////r31 = $r30;Aspect.aspectOf().ajc$after$Aspect$2$36f01b1c(ajc$tjp0);throw r31;}Aspect.aspectOf().ajc$after$Aspect$2$36f01b1c(ajc$tjp0);}catch (Throwable $r36){/ LJH insert here /if ($r36 instanceof ExceptionInIntializerError) //throw($r36); ////r2 = $r36;Aspect.aspectOf().ajc$after$Aspect$2$36f01b1c(ajc$tjp1);throw r2;}Aspect.aspectOf().ajc$after$Aspect$2$36f01b1c(ajc$tjp1);}"}